[slack]
legacyToken = "{{ slack_web_legacytoken}}"
channel = "{{ slack_channel }}"
iconEmoji = "{{ slack_emoji }}"
authUser = "{{ slack_user }}"

[servers]

[servers.{{ server_key_file_name }}]
host = "{{ server_to_scan }}"
user = "{{ server_username }}"
keyPath = "/root/.ssh/{{ server_key_file_name }}"

